service:
  name: vimes

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  profile: personal-aws

functions:
  auth:
    handler: auth.authorize
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  graphql:
    handler: handler.graphql
    authorizer: auth
    events:
      - http:
          method: get
          path: graphql
          cors: true
      - http:
          method: post
          path: graphql
  graphiql:
    handler: handler.graphiql
    events:
      - http:
          method: get
          path: graphiql